# Generated by Django 5.1.4 on 2025-01-19 08:30

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nippo', '0005_nippomodel_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nippomodel',
            name='slug',
        ),
        migrations.AddField(
            model_name='nippomodel',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
